services:
  mfe.host:
    build:
      context: ./mfe.host
      dockerfile: infrastructure/Dockerfile
    image: mfehost
    container_name: mfehost
    stdin_open: true
    ports:
      - "${VITE_HOST_PORT}:80"

  mfe.assistant:
    build:
      context: ./mfe.assistant
      dockerfile: infrastructure/Dockerfile
    image: mfeassistant
    container_name: mfeassistant
    stdin_open: true
    ports:
      - "${VITE_ASSISTANT_PORT:-5001}:80"
