apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE}-deployment
  namespace: galaxy-ms
  labels:
    app: ${SERVICE}
    version: ${VERSION}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${SERVICE}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ${SERVICE}
        version: ${VERSION}
    spec:
      serviceAccountName: ${SERVICE}-service-account
      containers:
      - name: ${SERVICE}
        image: ${SERVICE}:${VERSION}
        imagePullPolicy: Never
        ports:
        - containerPort: ${VITE_ASSISTANT_PORT}
        envFrom:
          - configMapRef:
              name: ${SERVICE}-config
        securityContext:
        livenessProbe:
          httpGet:
            path: /health
            port: ${VITE_ASSISTANT_PORT}
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: ${VITE_ASSISTANT_PORT}
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
